services:
  app:
    container_name: redcap_docker-app-1
    build: app
    ports:
      - '8080:80'

    depends_on:
      - db
    volumes:
      - ../redcap_source/:/var/www/html/
      - ../tmp/:/var/www/html/temp:Z
      - ../edocs/:/var/www/html/edocs:Z

  db:
    container_name: redcap_docker-db-1
    image: mysql:8.1
    ports:
      - '3400:3306'
    env_file:
      - env/db.env
    restart: always
    tmpfs: /var/lib/mysql

  mailpit:
    container_name: redcap_docker-mailpit-1
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
